export const getData = () => [
  {
    id: "1",
    part_number: "27",
    part_name: "Dragline",
    price: "9741",
    discount: "19",
    brand: "at vulputate vitae",
  },
  {
    id: "2",
    part_number: "79",
    part_name: "Compactor",
    price: "9381",
    discount: "20",
    brand: "hac habitasse platea",
  },
  {
    id: "3",
    part_number: "20",
    part_name: "Trencher",
    price: "3718",
    discount: "15",
    brand: "accumsan odio",
  },
  {
    id: "4",
    part_number: "68",
    part_name: "Dragline",
    price: "9055",
    discount: "19",
    brand: "enim sit amet",
  },
  {
    id: "5",
    part_number: "26",
    part_name: "Trencher",
    price: "6884",
    discount: "12",
    brand: "venenatis turpis enim",
  },
  {
    id: "6",
    part_number: "70",
    part_name: "Excavator",
    price: "9372",
    discount: "13",
    brand: "tristique in",
  },
  {
    id: "7",
    part_number: "70",
    part_name: "Backhoe",
    price: "5388",
    discount: "15",
    brand: "nullam orci",
  },
  {
    id: "8",
    part_number: "28",
    part_name: "Scraper",
    price: "1717",
    discount: "7",
    brand: "neque libero convallis",
  },
  {
    id: "9",
    part_number: "75",
    part_name: "Dragline",
    price: "9529",
    discount: "10",
    brand: "viverra diam vitae",
  },
  {
    id: "10",
    part_number: "15",
    part_name: "Grader",
    price: "4317",
    discount: "16",
    brand: "justo in",
  },
  {
    id: "11",
    part_number: "21",
    part_name: "Dragline",
    price: "8673",
    discount: "9",
    brand: "posuere metus vitae",
  },
  {
    id: "12",
    part_number: "91",
    part_name: "Excavator",
    price: "6981",
    discount: "7",
    brand: "sit amet cursus",
  },
  {
    id: "13",
    part_number: "91",
    part_name: "Crawler",
    price: "3055",
    discount: "5",
    brand: "sapien cursus vestibulum",
  },
  {
    id: "14",
    part_number: "54",
    part_name: "Bulldozer",
    price: "1946",
    discount: "18",
    brand: "nisi vulputate nonummy",
  },
  {
    id: "15",
    part_number: "6",
    part_name: "Scraper",
    price: "7446",
    discount: "14",
    brand: "dis parturient montes",
  },
  {
    id: "16",
    part_number: "7",
    part_name: "Skid-Steer",
    price: "2132",
    discount: "14",
    brand: "libero rutrum ac",
  },
  {
    id: "17",
    part_number: "82",
    part_name: "Backhoe",
    price: "8389",
    discount: "10",
    brand: "vulputate justo in",
  },
  {
    id: "18",
    part_number: "98",
    part_name: "Dump Truck",
    price: "4180",
    discount: "20",
    brand: "risus dapibus",
  },
  {
    id: "19",
    part_number: "19",
    part_name: "Dump Truck",
    price: "8299",
    discount: "12",
    brand: "sed augue aliquam",
  },
  {
    id: "20",
    part_number: "12",
    part_name: "Dragline",
    price: "7826",
    discount: "10",
    brand: "blandit ultrices",
  },
  {
    id: "21",
    part_number: "71",
    part_name: "Dump Truck",
    price: "2462",
    discount: "18",
    brand: "libero quis",
  },
  {
    id: "22",
    part_number: "19",
    part_name: "Skid-Steer",
    price: "6465",
    discount: "5",
    brand: "et ultrices",
  },
  {
    id: "23",
    part_number: "52",
    part_name: "Bulldozer",
    price: "953",
    discount: "13",
    brand: "felis eu sapien",
  },
  {
    id: "24",
    part_number: "55",
    part_name: "Grader",
    price: "8287",
    discount: "12",
    brand: "morbi a",
  },
  {
    id: "25",
    part_number: "68",
    part_name: "Excavator",
    price: "901",
    discount: "13",
    brand: "pede malesuada in",
  },
  {
    id: "26",
    part_number: "79",
    part_name: "Dragline",
    price: "926",
    discount: "5",
    brand: "euismod scelerisque",
  },
  {
    id: "27",
    part_number: "74",
    part_name: "Backhoe",
    price: "5229",
    discount: "17",
    brand: "libero quis orci",
  },
  {
    id: "28",
    part_number: "29",
    part_name: "Crawler",
    price: "387",
    discount: "5",
    brand: "dui maecenas tristique",
  },
  {
    id: "29",
    part_number: "58",
    part_name: "Backhoe",
    price: "8162",
    discount: "9",
    brand: "in porttitor pede",
  },
  {
    id: "30",
    part_number: "13",
    part_name: "Scraper",
    price: "3991",
    discount: "16",
    brand: "lectus aliquam sit",
  },
  {
    id: "31",
    part_number: "63",
    part_name: "Backhoe",
    price: "4560",
    discount: "13",
    brand: "at lorem",
  },
  {
    id: "32",
    part_number: "40",
    part_name: "Crawler",
    price: "2732",
    discount: "10",
    brand: "cum sociis natoque",
  },
  {
    id: "33",
    part_number: "99",
    part_name: "Backhoe",
    price: "9469",
    discount: "14",
    brand: "aenean lectus",
  },
  {
    id: "34",
    part_number: "44",
    part_name: "Bulldozer",
    price: "9192",
    discount: "18",
    brand: "at ipsum ac",
  },
  {
    id: "35",
    part_number: "38",
    part_name: "Trencher",
    price: "8488",
    discount: "7",
    brand: "mattis egestas metus",
  },
  {
    id: "36",
    part_number: "63",
    part_name: "Scraper",
    price: "5100",
    discount: "17",
    brand: "amet turpis elementum",
  },
  {
    id: "37",
    part_number: "61",
    part_name: "Backhoe",
    price: "8948",
    discount: "15",
    brand: "enim lorem ipsum",
  },
  {
    id: "38",
    part_number: "53",
    part_name: "Crawler",
    price: "7679",
    discount: "9",
    brand: "ipsum ac",
  },
  {
    id: "39",
    part_number: "94",
    part_name: "Scraper",
    price: "2427",
    discount: "13",
    brand: "arcu sed augue",
  },
  {
    id: "40",
    part_number: "14",
    part_name: "Trencher",
    price: "6052",
    discount: "16",
    brand: "venenatis turpis enim",
  },
  {
    id: "41",
    part_number: "37",
    part_name: "Backhoe",
    price: "3219",
    discount: "11",
    brand: "massa volutpat",
  },
  {
    id: "42",
    part_number: "72",
    part_name: "Excavator",
    price: "6191",
    discount: "6",
    brand: "eu tincidunt",
  },
  {
    id: "43",
    part_number: "41",
    part_name: "Skid-Steer",
    price: "232",
    discount: "13",
    brand: "mi in porttitor",
  },
  {
    id: "44",
    part_number: "37",
    part_name: "Grader",
    price: "7666",
    discount: "13",
    brand: "habitasse platea dictumst",
  },
  {
    id: "45",
    part_number: "60",
    part_name: "Backhoe",
    price: "2613",
    discount: "5",
    brand: "augue luctus tincidunt",
  },
  {
    id: "46",
    part_number: "52",
    part_name: "Compactor",
    price: "3754",
    discount: "17",
    brand: "volutpat dui",
  },
  {
    id: "47",
    part_number: "62",
    part_name: "Scraper",
    price: "4396",
    discount: "5",
    brand: "eros elementum",
  },
  {
    id: "48",
    part_number: "94",
    part_name: "Dump Truck",
    price: "5694",
    discount: "12",
    brand: "volutpat quam",
  },
  {
    id: "49",
    part_number: "11",
    part_name: "Grader",
    price: "1731",
    discount: "11",
    brand: "potenti in eleifend",
  },
  {
    id: "50",
    part_number: "9",
    part_name: "Compactor",
    price: "5691",
    discount: "6",
    brand: "elementum nullam",
  },
  {
    id: "51",
    part_number: "62",
    part_name: "Grader",
    price: "2001",
    discount: "12",
    brand: "interdum venenatis",
  },
  {
    id: "52",
    part_number: "72",
    part_name: "Grader",
    price: "623",
    discount: "17",
    brand: "rutrum nulla nunc",
  },
  {
    id: "53",
    part_number: "38",
    part_name: "Excavator",
    price: "2166",
    discount: "16",
    brand: "risus dapibus augue",
  },
  {
    id: "54",
    part_number: "39",
    part_name: "Scraper",
    price: "6195",
    discount: "17",
    brand: "morbi quis",
  },
  {
    id: "55",
    part_number: "44",
    part_name: "Compactor",
    price: "416",
    discount: "15",
    brand: "sapien iaculis congue",
  },
  {
    id: "56",
    part_number: "84",
    part_name: "Crawler",
    price: "4112",
    discount: "13",
    brand: "interdum in",
  },
  {
    id: "57",
    part_number: "75",
    part_name: "Compactor",
    price: "3952",
    discount: "11",
    brand: "nulla neque",
  },
  {
    id: "58",
    part_number: "54",
    part_name: "Excavator",
    price: "8145",
    discount: "20",
    brand: "nibh quisque id",
  },
  {
    id: "59",
    part_number: "79",
    part_name: "Skid-Steer",
    price: "8497",
    discount: "12",
    brand: "sagittis nam",
  },
  {
    id: "60",
    part_number: "77",
    part_name: "Bulldozer",
    price: "1080",
    discount: "7",
    brand: "risus semper porta",
  },
  {
    id: "61",
    part_number: "73",
    part_name: "Compactor",
    price: "2080",
    discount: "13",
    brand: "ut tellus nulla",
  },
  {
    id: "62",
    part_number: "35",
    part_name: "Backhoe",
    price: "6346",
    discount: "13",
    brand: "nascetur ridiculus",
  },
  {
    id: "63",
    part_number: "34",
    part_name: "Excavator",
    price: "3854",
    discount: "19",
    brand: "ante vel ipsum",
  },
  {
    id: "64",
    part_number: "75",
    part_name: "Scraper",
    price: "4870",
    discount: "5",
    brand: "pede justo",
  },
  {
    id: "65",
    part_number: "28",
    part_name: "Excavator",
    price: "1578",
    discount: "13",
    brand: "lacinia sapien quis",
  },
  {
    id: "66",
    part_number: "50",
    part_name: "Bulldozer",
    price: "3518",
    discount: "18",
    brand: "ante nulla",
  },
  {
    id: "67",
    part_number: "48",
    part_name: "Skid-Steer",
    price: "5734",
    discount: "20",
    brand: "quam nec",
  },
  {
    id: "68",
    part_number: "47",
    part_name: "Excavator",
    price: "3143",
    discount: "14",
    brand: "luctus et",
  },
  {
    id: "69",
    part_number: "58",
    part_name: "Trencher",
    price: "3780",
    discount: "7",
    brand: "lobortis est",
  },
  {
    id: "70",
    part_number: "59",
    part_name: "Dragline",
    price: "262",
    discount: "10",
    brand: "convallis eget",
  },
  {
    id: "71",
    part_number: "98",
    part_name: "Bulldozer",
    price: "4897",
    discount: "14",
    brand: "augue vestibulum",
  },
  {
    id: "72",
    part_number: "88",
    part_name: "Trencher",
    price: "6005",
    discount: "8",
    brand: "in tempus",
  },
  {
    id: "73",
    part_number: "67",
    part_name: "Crawler",
    price: "1265",
    discount: "17",
    brand: "sagittis dui vel",
  },
  {
    id: "74",
    part_number: "69",
    part_name: "Crawler",
    price: "2025",
    discount: "14",
    brand: "at feugiat non",
  },
  {
    id: "75",
    part_number: "6",
    part_name: "Backhoe",
    price: "5658",
    discount: "5",
    brand: "integer a",
  },
  {
    id: "76",
    part_number: "58",
    part_name: "Grader",
    price: "7343",
    discount: "15",
    brand: "penatibus et",
  },
  {
    id: "77",
    part_number: "13",
    part_name: "Crawler",
    price: "375",
    discount: "8",
    brand: "lacus at",
  },
  {
    id: "78",
    part_number: "34",
    part_name: "Scraper",
    price: "9914",
    discount: "5",
    brand: "diam in magna",
  },
  {
    id: "79",
    part_number: "12",
    part_name: "Grader",
    price: "8631",
    discount: "14",
    brand: "lacinia aenean",
  },
  {
    id: "80",
    part_number: "63",
    part_name: "Compactor",
    price: "4550",
    discount: "10",
    brand: "nam nulla integer",
  },
  {
    id: "81",
    part_number: "28",
    part_name: "Dragline",
    price: "2457",
    discount: "13",
    brand: "phasellus id",
  },
  {
    id: "82",
    part_number: "31",
    part_name: "Crawler",
    price: "3717",
    discount: "10",
    brand: "quam sapien",
  },
  {
    id: "83",
    part_number: "34",
    part_name: "Compactor",
    price: "6903",
    discount: "16",
    brand: "porttitor lorem id",
  },
  {
    id: "84",
    part_number: "45",
    part_name: "Grader",
    price: "6122",
    discount: "19",
    brand: "ligula pellentesque",
  },
  {
    id: "85",
    part_number: "82",
    part_name: "Grader",
    price: "7082",
    discount: "13",
    brand: "nunc vestibulum ante",
  },
  {
    id: "86",
    part_number: "87",
    part_name: "Dump Truck",
    price: "305",
    discount: "15",
    brand: "vitae nisl aenean",
  },
  {
    id: "87",
    part_number: "7",
    part_name: "Dragline",
    price: "311",
    discount: "13",
    brand: "potenti nullam porttitor",
  },
  {
    id: "88",
    part_number: "80",
    part_name: "Compactor",
    price: "5114",
    discount: "5",
    brand: "amet consectetuer",
  },
  {
    id: "89",
    part_number: "86",
    part_name: "Excavator",
    price: "9076",
    discount: "7",
    brand: "praesent id",
  },
  {
    id: "90",
    part_number: "9",
    part_name: "Compactor",
    price: "1877",
    discount: "13",
    brand: "et ultrices posuere",
  },
  {
    id: "91",
    part_number: "68",
    part_name: "Grader",
    price: "7947",
    discount: "7",
    brand: "a nibh in",
  },
  {
    id: "92",
    part_number: "6",
    part_name: "Trencher",
    price: "2420",
    discount: "13",
    brand: "vulputate elementum nullam",
  },
  {
    id: "93",
    part_number: "50",
    part_name: "Skid-Steer",
    price: "1234",
    discount: "13",
    brand: "fusce lacus purus",
  },
  {
    id: "94",
    part_number: "76",
    part_name: "Bulldozer",
    price: "2237",
    discount: "18",
    brand: "lectus vestibulum",
  },
  {
    id: "95",
    part_number: "23",
    part_name: "Skid-Steer",
    price: "7696",
    discount: "5",
    brand: "vestibulum sed",
  },
  {
    id: "96",
    part_number: "27",
    part_name: "Scraper",
    price: "6859",
    discount: "18",
    brand: "tincidunt in leo",
  },
  {
    id: "97",
    part_number: "36",
    part_name: "Bulldozer",
    price: "3196",
    discount: "14",
    brand: "vestibulum ac",
  },
  {
    id: "98",
    part_number: "97",
    part_name: "Dragline",
    price: "9864",
    discount: "6",
    brand: "lorem ipsum dolor",
  },
  {
    id: "99",
    part_number: "95",
    part_name: "Crawler",
    price: "6293",
    discount: "16",
    brand: "in lectus",
  },
  {
    id: "100",
    part_number: "46",
    part_name: "Excavator",
    price: "2668",
    discount: "19",
    brand: "pulvinar sed nisl",
  },
]
